version: '3.8'

services:
  web:
    image: todo-fastapi
    ports:
      - 80:80
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env.db
  redis:
    image: redis:alpine

volumes:
  postgres_data: